# src/exact_poly.py
r"""Exact rational polynomial helpers and Groebner-basis answers to the questions ``src.invariants`` raises.

Two questions ``src.invariants`` poses but cannot answer on its own:

- does the Vandermonde divide a given antisymmetric polynomial, exactly and over Q?
- what, if anything, is in the node of a polynomial trial function *besides* the coincidence set?

Both are decisions, so everything here goes through ``src.exact_gb`` (a rational Buchberger
vendored from agca_jax) rather than a floating-point engine: a floating Groebner basis can report
``1 in I`` for an ideal that is not the unit ideal, which would silently turn "no extra nodes"
into a wrong answer.

Groebner is offline tooling
---------------------------
Buchberger is doubly exponential in the worst case. Nothing here belongs inside a Monte Carlo
loop; it is for certifying small cases and for generating structure that then gets hard-coded.
Budget n <= 4 or so, and expect saturation (which adjoins a variable and needs LEX) to be the
expensive one.

A polynomial is a plain ``dict`` from exponent tuple to ``Fraction``, which is exactly
``src.exact_gb``'s own representation.
"""
from __future__ import annotations

import itertools as it
from fractions import Fraction
from typing import Iterable, Sequence

import src.exact_gb as EG

Term = tuple
ExactPoly = dict

# --------------------------------------------------------------------------- #
# Polynomials over Q as plain dicts
# --------------------------------------------------------------------------- #

def term_dict(terms) -> ExactPoly:
  r"""Normalize ``{exponent tuple: coefficient}`` to exact rationals, dropping zeros."""
  out = {}
  for exps, coeff in terms.items():
    c = Fraction(coeff)
    if c:
      out[tuple(int(e) for e in exps)] = out.get(tuple(int(e) for e in exps), Fraction(0)) + c
  return {e: c for e, c in out.items() if c}


def vandermonde_poly(n: int) -> ExactPoly:
  r"""The Vandermonde ``prod_{i<j} (x_j - x_i)`` expanded as an exact term dict.

  Built by repeated multiplication rather than from the Leibniz formula, so it stays honest for
  the small n this module is for.
  """
  poly: ExactPoly = {(0,) * n: Fraction(1)}
  for i, j in it.combinations(range(n), 2):
    factor = {}
    ej = [0] * n
    ej[j] = 1
    ei = [0] * n
    ei[i] = 1
    factor[tuple(ej)] = Fraction(1)
    factor[tuple(ei)] = Fraction(-1)
    poly = multiply(poly, factor)
  return poly


def multiply(f: ExactPoly, g: ExactPoly) -> ExactPoly:
  r"""Product of two exact term dicts."""
  out: ExactPoly = {}
  for ef, cf in f.items():
    for eg, cg in g.items():
      key = tuple(a + b for a, b in zip(ef, eg))
      out[key] = out.get(key, Fraction(0)) + cf * cg
  return {e: c for e, c in out.items() if c}


def monomial(exponents: Sequence[int], coeff=1) -> ExactPoly:
  r"""A single term, as an exact term dict."""
  return {tuple(int(e) for e in exponents): Fraction(coeff)}


# --------------------------------------------------------------------------- #
# The two questions worth asking a Groebner engine
# --------------------------------------------------------------------------- #

def divides_vandermonde(f, n: int) -> bool:
  r"""Decide exactly whether the Vandermonde divides ``f`` in Q[x_1..x_n].

  Tested as membership of ``f`` in the principal ideal generated by the Vandermonde, which for a
  principal ideal is exactly divisibility. Every antisymmetric polynomial must pass; this is the
  machine-checkable form of the factorization theorem in ``src.invariants``.
  """
  f = term_dict(f)
  gens = [EG.poly_from_terms(vandermonde_poly(n), n)]
  gb = EG.buchberger(gens, EG.GRLEX)
  return bool(EG.ideal_membership(gb, EG.poly_from_terms(f, n), EG.GRLEX))


def extra_node_ideal(f, n: int) -> list:
  r"""Generators of ``(f) : V^infinity``, the part of the node that is not a coincidence.

  Saturating the principal ideal of a polynomial trial function by the Vandermonde removes the
  coincidence hyperplanes, which every antisymmetric function must vanish on. What is left is the
  *spurious* nodal surface -- the nodes the ansatz has that the exact ground state need not.

  Returned as a list of exact term dicts. ``[{(0,...,0): 1}]`` means the unit ideal, i.e. no
  extra nodes: the node is exactly the coincidence set. Use ``has_no_extra_nodes`` for the
  boolean.

  Saturation adjoins a variable and requires LEX, so this is the expensive call here.
  """
  f = term_dict(f)
  gens = [EG.poly_from_terms(f, n)]
  vdm = EG.poly_from_terms(vandermonde_poly(n), n)
  sat = EG.saturate(gens, vdm, order=EG.LEX)
  return [dict(g) for g in sat]


def has_no_extra_nodes(f, n: int) -> bool:
  r"""True when the node of ``f`` is exactly the coincidence set and nothing more."""
  sat = extra_node_ideal(f, n)
  zero = (0,) * n
  return len(sat) == 1 and set(sat[0].keys()) == {zero}


# --------------------------------------------------------------------------- #
# Plucker
# --------------------------------------------------------------------------- #

def plucker_ideal(n_orb: int, n_occ: int) -> list:
  r"""The Plucker quadrics of ``Gr(n_occ, n_orb)`` as exact polynomials in the coordinates.

  Variables are indexed as ``src.grassmann.plucker_indices(n_orb, n_occ)``. Returned as term
  dicts so they can be fed straight back through
  ``groebner_basis`` to get a reduced basis of the ideal.

  Deduplicated up to sign, so for ``Gr(2, n)`` this returns the classical ``binom(n, 4)``
  three-term relations. The reduced Groebner basis is generally larger than this minimal
  generating set -- for ``Gr(2, 5)`` it has six elements, not five.
  """
  import src.grassmann as grassmann  # local import: grassmann does not depend on this module

  n_vars = len(grassmann.plucker_indices(n_orb, n_occ))
  out = []
  for terms in grassmann._relation_terms(n_orb, n_occ):
    poly: ExactPoly = {}
    for coeff, a, b in terms:
      exps = [0] * n_vars
      exps[a] += 1
      exps[b] += 1
      key = tuple(exps)
      poly[key] = poly.get(key, Fraction(0)) + Fraction(coeff)
    poly = {e: c for e, c in poly.items() if c}
    if poly:
      out.append(poly)
  return out


def groebner_basis(gens: Iterable, n_vars: int, order: str = "grlex") -> list:
  r"""Reduced exact Groebner basis of ``gens``, as a list of term dicts.

  ``order`` is ``"grlex"`` or ``"lex"``; the exact engine does not implement grevlex.
  """
  gens = [term_dict(g) for g in gens]
  key = {"grlex": EG.GRLEX, "lex": EG.LEX}[order.lower()]
  basis = EG.buchberger([EG.poly_from_terms(g, n_vars) for g in gens], key)
  return [dict(g) for g in basis]
