# src/permutations.py
from __future__ import annotations
from collections import defaultdict
from collections.abc import Sequence
import dataclasses as dcls
import math
import numpy as onp
import itertools as it
import re

Permutation = tuple[int, ...]
_CYCLE_BLOCK_RE = re.compile(r"\(([^()]*)\)")

# conversion to int utils
def int_vec(v):
  return tuple(onp.rint(onp.asarray(v)).astype(int).tolist())

def int_mat(M):
  return onp.rint(onp.asarray(M)).astype(int)



def identity_perm(n: int) -> Permutation:
  return tuple(range(n))


def inverse_perm(p: Permutation) -> Permutation:
  inv = [0] * len(p)
  for i, j in enumerate(p):
    inv[j] = i
  return tuple(inv)


def cycle_type(p: Permutation) -> tuple[int, ...]:
  r""" cycle type from permutation `p` """
  seen = set()
  parts = []
  for i in range(len(p)):
    if i in seen:
      continue
    j = i
    k = 0
    while j not in seen:
      seen.add(j)
      j = p[j]
      k += 1
    parts.append(k)
  return tuple(sorted(parts, reverse=True))


def perm_hom_tup(items, image_fn):
  r""" permutation represented as tuple """
  lookup = {item: i for i, item in enumerate(items)}
  return tuple(lookup[image_fn(item)] for item in items)

def perm_hom(perm):
  r""" permutation representation homom """
  n = len(perm)
  M = onp.zeros((n, n), dtype=int)
  for j, i in enumerate(perm):
    # TODO why flipped?
    M[i, j] = 1
  return M


def perm_char(p: Permutation):
  return int(onp.trace(perm_hom(p)))


def compose_perm(p, q):
  return tuple(p[q[i]] for i in range(len(p)))


def perm_from_cycles(
  cycles: Sequence[Sequence[int]],
  *,
  degree: int | None = None,
  one_based: bool = True,
) -> Permutation:
  r"""Build a tuple permutation from cycle data.

  The returned permutation uses the existing internal convention
  ``p[i] = g(i)`` on ``{0, ..., n-1}``. Multiple cycles are composed in the
  order they are written, so ``[(1, 2), (2, 3)]`` means ``(1,2)(2,3)``.
  """

  cycles = tuple(tuple(int(label) for label in cycle) for cycle in cycles)
  if degree is None:
    labels = [label for cycle in cycles for label in cycle]
    if not labels:
      raise ValueError("degree is required when no nontrivial cycles are supplied")
    degree = max(labels)

  if degree < 0:
    raise ValueError("degree must be nonnegative")

  offset = 1 if one_based else 0
  lo = offset
  hi = degree - 1 + offset
  out = identity_perm(degree)

  for cycle in cycles:
    if len(cycle) <= 1:
      continue
    shifted = tuple(label - offset for label in cycle)
    if len(set(shifted)) != len(shifted):
      raise ValueError(f"cycle contains repeated labels: {cycle!r}")
    if any(label < lo or label > hi for label in cycle):
      raise ValueError(
        f"cycle labels must lie in [{lo}, {hi}], got {cycle!r}"
      )

    cycle_perm = list(range(degree))
    for src, dst in zip(shifted, shifted[1:] + shifted[:1]):
      cycle_perm[src] = dst
    out = compose_perm(out, tuple(cycle_perm))

  return out


def perm_from_cycle_notation(
  notation: str,
  *,
  degree: int | None = None,
  one_based: bool = True,
) -> Permutation:
  r"""Parse cycle notation like ``"(1,2,3)(4,5)"`` into tuple form."""
  cycles: list[tuple[int, ...]] = []
  pos = 0
  for match in _CYCLE_BLOCK_RE.finditer(notation):
    if notation[pos:match.start()].strip():
      raise ValueError(f"invalid cycle notation: {notation!r}")
    body = match.group(1).strip()
    if body:
      pieces = [piece for piece in re.split(r"[\s,]+", body) if piece]
      cycles.append(tuple(int(piece) for piece in pieces))
    else:
      cycles.append(tuple())
    pos = match.end()

  if notation[pos:].strip() or not cycles:
    raise ValueError(f"invalid cycle notation: {notation!r}")

  return perm_from_cycles(cycles, degree=degree, one_based=one_based)


def generated_group(
  generators: Sequence[Permutation],
  *,
  name: str = "",
  max_order: int | None = None,
) -> "PermutationGroup":
  r"""Close the subgroup generated by tuple permutations."""

  gens = tuple(tuple(int(i) for i in gen) for gen in generators)
  if not gens:
    raise ValueError("at least one generator is required")

  degree = len(gens[0])
  expected = tuple(range(degree))
  for gen in gens:
    if len(gen) != degree:
      raise ValueError("all generators must have the same degree")
    if tuple(sorted(gen)) != expected:
      raise ValueError(f"invalid permutation generator: {gen!r}")

  ident = identity_perm(degree)
  seen = {ident}
  elements = [ident]
  frontier = [ident]
  while frontier:
    current = frontier.pop()
    for gen in gens:
      for candidate in (compose_perm(gen, current), compose_perm(current, gen)):
        if candidate in seen:
          continue
        seen.add(candidate)
        elements.append(candidate)
        frontier.append(candidate)
        if max_order is not None and len(elements) > max_order:
          raise ValueError(
            "generated group exceeded max_order; "
            "check the generators or raise max_order"
          )

  return PermutationGroup(tuple(elements), name=name)

def perm_power(p, k):
  out = identity_perm(len(p))
  for _ in range(k):
    out = compose_perm(p, out)
  return out


def sign_perm(p):
  inversions = 0
  for i in range(len(p)):
    for j in range(i + 1, len(p)):
      inversions += p[i] > p[j]
  return -1 if inversions % 2 else 1


def fixed_points(p: Permutation) -> int:
  return sum(i == p[i] for i in range(len(p)))


def conjugate_perm(p: Permutation, g: Permutation) -> Permutation:
  r""" Conjugate `p` by `g`, i.e., return `g p g^{-1}`. """
  ginv = inverse_perm(g)
  return compose_perm(g, compose_perm(p, ginv))


def conjugacy_class(p: Permutation, group: tuple[Permutation, ...] | list[Permutation]) -> tuple[Permutation, ...]:
  r"""Conjugacy class of `p` inside the supplied permutation group."""
  seen = set()
  cls = []
  for g in group:
    q = conjugate_perm(p, g)
    if q in seen:
      continue
    seen.add(q)
    cls.append(q)
  return tuple(cls)


def conjugacy_classes(group: tuple[Permutation, ...] | list[Permutation]) -> tuple[tuple[Permutation, ...], ...]:
  r"""Partition a finite permutation group into subgroup conjugacy classes."""
  remaining = set(group)
  classes = []
  while remaining:
    p = next(iter(remaining))
    cls = conjugacy_class(p, group)
    classes.append(cls)
    remaining.difference_update(cls)
  return tuple(classes)


def conjugacy_class_representatives(
  group: tuple[Permutation, ...] | list[Permutation],
) -> tuple[Permutation, ...]:
  r"""Deterministic representatives for subgroup conjugacy classes."""
  return tuple(sorted(min(cls) for cls in conjugacy_classes(group)))


def classes_by_cycle_type(
  group: tuple[Permutation, ...] | list[Permutation]
) -> dict[tuple[int, ...], tuple[Permutation, ...]]:
  r"""Group permutations by cycle type.

  For the full symmetric group `S_n`, these are exactly the conjugacy classes.
  For a subgroup, same cycle type does not necessarily imply conjugacy.
  """
  classes = defaultdict(list)
  for p in group:
    classes[cycle_type(p)].append(p)
  return {ct: tuple(perms) for ct, perms in classes.items()}


def class_size_symmetric(cycle_shape: tuple[int, ...]) -> int:
  r"""Size of the `S_n` conjugacy class with the given cycle type."""
  n = sum(cycle_shape)
  multiplicities = defaultdict(int)
  for part in cycle_shape:
    multiplicities[part] += 1

  denom = 1
  for part, mult in multiplicities.items():
    denom *= part ** mult
    denom *= math.factorial(mult)
  return math.factorial(n) // denom


def centralizer_size_symmetric(cycle_shape: tuple[int, ...]) -> int:
  r""" Size of the centralizer in `S_n` of a permutation with the given cycle type. """
  n = math.factorial(sum(cycle_shape))
  return n // class_size_symmetric(cycle_shape)


# TODO this should be registered as a pytree-dataclass for backprop eventually
# However, I will then need to change the method of composition, as this is not 
# really supported through JIT compilation
# @dcls.dataclass(frozen=True)
class PermElt(tuple):
  # perm: Permutation
  # name: str = ""
  def __new__(cls, *a):
    return tuple.__new__(PermElt, a)

  def __rmul__(self, other: PermElt):
    r""" im thinking right-multiplication should be composition """
    return PermElt(compose_perm(other, self))

  def __mul__(self, other: PermElt):
    r""" TODO left-multiplication should be action??? But how to implement... """
    raise NotImplementedError

  def __call__(self, other: PermElt):
    r""" TODO or should __call__ be action? or call is just composition? 
    idk... gotta decide """
    return PermElt(compose_perm(self, other))
  
  # def __getitem__(self, key):
  #   return self.perm[key]
  
  # def __hash__(self):
  #   r""" hash the owned object """
  #   return hash(self.perm)

  def inv(self):
    return inverse_perm(self)
  # def conj(self):
    # return conjugate_perm()


@dcls.dataclass(frozen=True)
class PermutationGroup:
  r""" permutation group structure """
  elements: tuple[Permutation, ...]
  name: str = ""

  @classmethod
  def symmetric(cls, n: int, *, name: str | None = None) -> "PermutationGroup":
    return cls(tuple(it.permutations(range(n))), name=name or f"S{n}")

  @classmethod
  def generated(
    cls,
    generators: Sequence[Permutation],
    *,
    name: str = "",
    max_order: int | None = None,
  ) -> "PermutationGroup":
    return generated_group(generators, name=name, max_order=max_order)

  def __iter__(self):
    return iter(self.elements)

  def __len__(self) -> int:
    return len(self.elements)

  @property
  def order(self) -> int:
    return len(self.elements)

  @property
  def degree(self) -> int:
    return len(self.elements[0]) if self.elements else 0

  def conjugacy_class(self, p: Permutation) -> tuple[Permutation, ...]:
    return conjugacy_class(p, self.elements)

  def conjugacy_classes(self) -> tuple[tuple[Permutation, ...], ...]:
    r""" conjugacy classes of permutation group """
    return conjugacy_classes(self.elements)

  def conjugacy_class_representatives(self) -> tuple[Permutation, ...]:
    return conjugacy_class_representatives(self.elements)

  def classes_by_cycle_type(self) -> dict[tuple[int, ...], tuple[Permutation, ...]]:
    return classes_by_cycle_type(self.elements)

  def class_sizes_by_cycle_type(self) -> dict[tuple[int, ...], int]:
    return {ct: len(cls) for ct, cls in self.classes_by_cycle_type().items()}
